services:
  # Backend API
  - type: web
    name: guardbulldog-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        sync: false
    autoDeploy: true

  # PostgreSQL Database
databases:
  - name: guardbulldog-db
    databaseName: guardbulldog
    user: guardbulldog
